// src/angular/app.component.ts
import { Component, ChangeDetectorRef, Inject, Injectable } from '@angular/core'
import { HttpClient } from '@angular/common/http';
import { Location } from '@angular/common';
import e from '../event-bus'

@Component({
  selector: 'AngularApp',
  // comment out because of missing html loader and no webpack
  // templateUrl: require('./app.component.html')
  // styleUrls: ['./app.component.css'],
  template: `
  <div style="margin: 40px 30px 0 30px; border-top: solid 1px;">
    <div style="margin-top: 90px; display: inline-block; width: 389px;">
      <h1>This was written in Angular</h1>
      <p>
      <button (click)="sendMessage()">Send a message to Angular</button>
      </p> 
      <p>{{message}}</p>
    </div>
    <img style="display: inline-block; 
      padding: 0 88px 0 178px;
      width:200px;" src="../../public/angularLogo.png" alt="angular Logo"/>
  </div> 
      `,
})

export default class AppComponent {
  message: string = "The message from React should appear here 👈";

  constructor(@Inject(ChangeDetectorRef) private changeDetector) {
    e.on('messageFromReact', message => {
      this.message = message
      this.changeDetector.detectChanges()
    })
  }

  sendMessage() {
    e.emit('messageFromAngular', 'Yip! Hello from Angular! 👍')
  }
}

<div>
  <h1>This was written in Angular</h1>
  <h1>Hello {{ title }}</h1>
</div>

// src/react/components/app.js
import React, { useState, useEffect } from "react";
import "./app.css";
import e from "../../event-bus";

const App = () => {
  const [message, setMessage] = useState(
    "When Angular receives message, we should see a confirmation here 👈"
  );

  useEffect(() => {
    e.on("messageFromAngular", setMessage);
    return () => e.off("messageFromAngular", setMessage);
  }, []);

  const sendMessage = () => {
    e.emit("messageFromReact", "Hello from React 👌");
  };

  return (
    <div style={{ margin: "0 30px 0 30px" }}>
      <div
        style={{
          margin: "10px 0 40px 0",
          display: "inline-block",
          width: "460px"
        }}
      >
        <h1>This was written in React</h1>
        <p>
          <button onClick={sendMessage}>Send a message to Angular</button>
        </p>
        <p>{message}</p>
      </div>
      <img
        style={{
          display: "inline-block",
          width: "30%",
          padding: "0 100px 0 100px",
          width: "200px"
        }}
        src="../../public/reactLogo512.png"
        alt="react Logo"
      />
    </div>
  );
};
export default App;
